services:
  # Backend API Service
  - type: web
    name: finance-analytics-api
    env: python
    buildCommand: |
      cd backend &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      cd backend &&
      gunicorn --bind 0.0.0.0:$PORT run:app
    plan: free
    healthCheckPath: /health-check
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

# Environment Variables Documentation
# Set these manually in your Render.com service dashboard:
#
# Database Configuration:
# - POSTGRES_HOST: Your PostgreSQL hostname (e.g., dpg-xxx.oregon-postgres.render.com)
# - POSTGRES_PORT: PostgreSQL port (usually 5432)
# - POSTGRES_USER: PostgreSQL username
# - POSTGRES_PASSWORD: PostgreSQL password
# - POSTGRES_DB: PostgreSQL database name
#
# External Services:
# - MONGO_URI: MongoDB connection string (e.g., mongodb+srv://user:pass@cluster.mongodb.net/dbname)
# - OPENROUTER_API_KEY: OpenRouter API key for AI features (optional)
#
# Security:
# - JWT_SECRET: Auto-generated by Render.com for JWT token signing